// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR6Nr9vQs6WS_Yt8IOMLqy7a3E-b_JTFM',
    appId: '1:969160913422:web:752421b47db00cd1db025f',
    messagingSenderId: '969160913422',
    projectId: 'quiz-app-4d8e0',
    authDomain: 'quiz-app-4d8e0.firebaseapp.com',
    storageBucket: 'quiz-app-4d8e0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYAtx_sV7ehkFQ0yuPuayJvMfR7kiKSTk',
    appId: '1:969160913422:android:2c3e32050d808782db025f',
    messagingSenderId: '969160913422',
    projectId: 'quiz-app-4d8e0',
    storageBucket: 'quiz-app-4d8e0.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR6Nr9vQs6WS_Yt8IOMLqy7a3E-b_JTFM',
    appId: '1:969160913422:web:256c8520838c0b79db025f',
    messagingSenderId: '969160913422',
    projectId: 'quiz-app-4d8e0',
    authDomain: 'quiz-app-4d8e0.firebaseapp.com',
    storageBucket: 'quiz-app-4d8e0.appspot.com',
  );
}
